spring:
  profiles:
    active: dev-oracle

  messages:
    basename: messages
    encoding: UTF-8

  # mvn spring-boot:run -Dspring-boot.run.profiles=oracle
    # java -jar sua-api.jar --spring.profiles.active=oracle
  # SPRING_PROFILES_ACTIVE=oracle
