spring:
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553243
    password: 180600
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.OracleDialect