spring:
  profiles:
    active: dev-postgresql

    # mvn spring-boot:run -Dspring-boot.run.profiles=oracle
    # java -jar sua-api.jar --spring.profiles.active=oracle
    # SPRING_PROFILES_ACTIVE=oracle